<template>
  <div class="animate-fade-in pr-wrap">
    <!-- Header -->
    <div class="pr-head">
      <div class="pr-head-icon grad-violet"><FileBarChart class="w-6 h-6" /></div>
      <div class="pr-head-info">
        <h1 class="pr-title">My Preparation Report</h1>
        <p class="pr-sub">{{ auth.user?.name || 'Student' }} · Grade {{ grade }} · {{ board }}</p>
      </div>
      <button type="button" class="btn-secondary text-xs pr-print" @click="print()"><Printer class="w-3.5 h-3.5" /> Print</button>
    </div>

    <!-- Empty state -->
    <div v-if="!student.totalTests" class="card pr-empty">
      <ClipboardList class="w-12 h-12 mb-2 opacity-40" />
      <p class="pr-empty-title">No tests yet</p>
      <p class="pr-empty-sub">Take a Self Test, Daily Test or a Board paper, and your full preparation report builds here automatically.</p>
      <RouterLink to="/app/self-test" class="btn-primary mt-3"><Play class="w-4 h-4" /> Start a Self Test</RouterLink>
    </div>

    <template v-else>
      <!-- KPIs -->
      <div class="pr-kpis">
        <div class="pr-kpi"><div class="pr-kpi-val">{{ student.totalTests }}</div><div class="pr-kpi-lbl">Tests taken</div></div>
        <div class="pr-kpi"><div class="pr-kpi-val">{{ student.avgPercent }}%</div><div class="pr-kpi-lbl">Average score</div></div>
        <div class="pr-kpi"><div class="pr-kpi-val">{{ passRate }}%</div><div class="pr-kpi-lbl">Pass rate</div></div>
        <div class="pr-kpi"><div class="pr-kpi-val">{{ student.monthlyTests }}</div><div class="pr-kpi-lbl">This month</div></div>
      </div>

      <div class="pr-grid">
        <!-- Subject performance -->
        <div class="card pr-card">
          <div class="pr-card-title">Subject Performance</div>
          <div v-for="s in bySubject" :key="s.subject" class="pr-subj">
            <div class="pr-subj-top">
              <span class="pr-subj-name">{{ s.subject }}</span>
              <span :class="statusBadge(s.status)">{{ s.status }}</span>
            </div>
            <div class="pr-bar"><span :style="{ width: s.avg + '%', background: barColor(s.avg) }" /></div>
            <div class="pr-subj-meta">{{ s.avg }}% avg · {{ s.tests }} test{{ s.tests === 1 ? '' : 's' }} · best {{ s.best }}%</div>
          </div>
        </div>

        <!-- Score trend -->
        <div class="card pr-card">
          <div class="pr-card-title">Score Trend <span class="pr-card-hint">last {{ trend.length }} tests</span></div>
          <div class="pr-trend">
            <div v-for="(v, i) in trend" :key="i" class="pr-trend-col" :title="v + '%'">
              <span class="pr-trend-bar" :style="{ height: Math.max(4, v) + '%', background: barColor(v) }" />
            </div>
          </div>
          <div class="pr-trend-axis"><span>0%</span><span>100%</span></div>
        </div>
      </div>

      <!-- Focus + recent -->
      <div class="pr-grid">
        <div class="card pr-card">
          <div class="pr-card-title">What to focus on</div>
          <ul class="pr-focus">
            <li v-for="s in weakest" :key="s.subject" class="pr-focus-item">
              <AlertTriangle class="w-3.5 h-3.5 shrink-0" style="color:var(--t-warn)" />
              <span><strong>{{ s.subject }}</strong> — {{ s.avg }}% avg. Revise weak topics and retake a test.</span>
            </li>
            <li v-if="!weakest.length" class="pr-focus-item">
              <CheckCircle2 class="w-3.5 h-3.5 shrink-0" style="color:var(--t-success)" />
              <span>Great consistency — keep practising to stay exam‑ready.</span>
            </li>
          </ul>
        </div>
        <div class="card pr-card">
          <div class="pr-card-title">Recent tests</div>
          <div v-for="t in recent" :key="t.id" class="pr-recent">
            <span class="pr-recent-subj">{{ t.subject }}</span>
            <span class="pr-recent-type">{{ t.type }}</span>
            <span class="pr-recent-score" :style="{ color: barColor(pct(t)) }">{{ t.score }}/{{ t.total }}</span>
            <span class="pr-recent-date">{{ fmtDate(t.date) }}</span>
          </div>
        </div>
      </div>

      <!-- AI report -->
      <div class="card pr-card pr-ai">
        <div class="pr-card-title"><Sparkles class="w-4 h-4" style="color:var(--t-accent)" /> AI Readiness Summary</div>
        <p v-if="!aiSummary && !aiLoading" class="pr-ai-hint">Saathi reads your real test history and writes a readiness summary with next steps.</p>
        <button v-if="!aiSummary" type="button" class="btn-primary" :disabled="aiLoading" @click="generateSummary">
          <Sparkles class="w-4 h-4" /> {{ aiLoading ? 'Analysing your results…' : 'Generate AI Summary' }}
        </button>
        <p v-if="aiSummary" class="pr-ai-text">{{ aiSummary }}</p>
        <p v-if="aiSummary" class="pr-ai-engine">Generated by Saathi from your real test data.</p>
      </div>
    </template>
  </div>
</template>

<script setup>
import { ref, computed } from 'vue'
import { FileBarChart, Printer, ClipboardList, Play, AlertTriangle, CheckCircle2, Sparkles } from '@lucide/vue'
import { useStudentStore } from '@/stores/student'
import { useAuthStore } from '@/stores/auth'
import { saathiChat } from '@/services/ollamaService'

const student = useStudentStore()
const auth = useAuthStore()
const grade = computed(() => auth.user?.gradeCode ?? 9)
const board = computed(() => (auth.user?.board ? `${auth.user.board} Board` : 'Balochistan Board') + ' (BISE)')

const pct = (t) => (t.total ? Math.round((t.score / t.total) * 100) : 0)
const passRate = computed(() => student.totalTests ? Math.round((student.passedTests / student.totalTests) * 100) : 0)

const bySubject = computed(() => {
  const map = {}
  for (const t of student.testRecords) {
    const s = t.subject || 'General'
    if (!map[s]) map[s] = { subject: s, tests: 0, sum: 0, best: 0 }
    const p = pct(t)
    map[s].tests++; map[s].sum += p; map[s].best = Math.max(map[s].best, p)
  }
  return Object.values(map)
    .map((m) => {
      const avg = Math.round(m.sum / m.tests)
      return { ...m, avg, status: avg >= 85 ? 'Strong' : avg >= 60 ? 'On track' : 'Needs work' }
    })
    .sort((a, b) => a.avg - b.avg)
})
const weakest = computed(() => bySubject.value.filter((s) => s.avg < 60).slice(0, 4))
const recent = computed(() => student.testRecords.slice(0, 8))
const trend = computed(() => student.chartData.series[0]?.data || [])

function statusBadge(s) { return s === 'Strong' ? 'badge-green' : s === 'On track' ? 'badge-amber' : 'badge-red' }
function barColor(v) { return v >= 85 ? 'var(--t-success)' : v >= 60 ? 'var(--t-gold)' : 'var(--t-danger)' }
function fmtDate(d) { try { return new Date(d).toLocaleDateString('en-PK', { day: 'numeric', month: 'short' }) } catch { return '' } }
function print() { window.print() }

const aiSummary = ref('')
const aiLoading = ref(false)
async function generateSummary() {
  aiLoading.value = true
  const progress = bySubject.value.map((s) => ({ subject: s.subject, tests: s.tests, avg_score: s.avg, best: s.best }))
  const activity = student.testRecords.slice(0, 15).map((t) => ({
    date: (t.date || '').slice(0, 10), subject: t.subject, score: t.score, total: t.total, type: t.type,
  }))
  try {
    aiSummary.value = await saathiChat('exam_readiness_report', grade.value, {
      student_name: auth.user?.name || 'Student', language: 'english',
      progress_json: progress, activity_log_json: activity, exam_json: {}, syllabus_json: {},
      today_date: new Date().toISOString().slice(0, 10),
    }, 'Summarise my exam preparation from my real test history, and tell me the 3 most important next steps.')
  } catch {
    aiSummary.value = 'Could not generate the AI summary right now — please try again.'
  }
  aiLoading.value = false
}
</script>

<style scoped>
.pr-wrap { max-width: 960px; margin: 0 auto; display: flex; flex-direction: column; gap: 1rem; }
.pr-head { display: flex; align-items: center; gap: 0.85rem; }
.pr-head-icon { width: 46px; height: 46px; border-radius: 13px; display: flex; align-items: center; justify-content: center; color: #fff; flex-shrink: 0; }
.pr-head-info { flex: 1; min-width: 0; }
.pr-title { font-size: 1.3rem; font-weight: 800; color: var(--t-text1); font-family: 'Syne', sans-serif; line-height: 1.1; }
.pr-sub { font-size: 0.78rem; color: var(--t-text3); margin-top: 0.15rem; }
.pr-print { flex-shrink: 0; }

.pr-empty { display: flex; flex-direction: column; align-items: center; text-align: center; padding: 2.5rem 1rem; color: var(--t-text3); }
.pr-empty-title { font-size: 1rem; font-weight: 700; color: var(--t-text1); }
.pr-empty-sub { font-size: 0.84rem; max-width: 420px; margin-top: 0.25rem; }

.pr-kpis { display: grid; grid-template-columns: repeat(4, 1fr); gap: 0.75rem; }
@media (max-width: 600px) { .pr-kpis { grid-template-columns: repeat(2, 1fr); } }
.pr-kpi { background: var(--t-surface); border: 1px solid var(--t-border); border-radius: 14px; padding: 1rem; text-align: center; }
.pr-kpi-val { font-size: 1.5rem; font-weight: 800; color: var(--t-accent); font-family: 'Syne', sans-serif; }
.pr-kpi-lbl { font-size: 0.72rem; color: var(--t-text3); margin-top: 0.15rem; }

.pr-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; }
@media (max-width: 720px) { .pr-grid { grid-template-columns: 1fr; } }
.pr-card { padding: 1.1rem 1.2rem; }
.pr-card-title { display: flex; align-items: center; gap: 0.4rem; font-size: 0.88rem; font-weight: 700; color: var(--t-text1); margin-bottom: 0.85rem; }
.pr-card-hint { font-size: 0.68rem; font-weight: 500; color: var(--t-text3); }

.pr-subj { margin-bottom: 0.85rem; }
.pr-subj-top { display: flex; align-items: center; justify-content: space-between; margin-bottom: 0.3rem; }
.pr-subj-name { font-size: 0.84rem; font-weight: 600; color: var(--t-text1); }
.pr-bar { height: 8px; border-radius: 99px; background: var(--t-hover2); overflow: hidden; }
.pr-bar span { display: block; height: 100%; border-radius: 99px; transition: width 0.3s; }
.pr-subj-meta { font-size: 0.7rem; color: var(--t-text3); margin-top: 0.25rem; }

.pr-trend { display: flex; align-items: flex-end; gap: 3px; height: 120px; padding-top: 0.5rem; }
.pr-trend-col { flex: 1; height: 100%; display: flex; align-items: flex-end; }
.pr-trend-bar { width: 100%; border-radius: 3px 3px 0 0; min-height: 4px; transition: height 0.3s; }
.pr-trend-axis { display: flex; justify-content: space-between; font-size: 0.62rem; color: var(--t-text3); margin-top: 0.3rem; }

.pr-focus { list-style: none; margin: 0; padding: 0; display: flex; flex-direction: column; gap: 0.6rem; }
.pr-focus-item { display: flex; gap: 0.5rem; align-items: flex-start; font-size: 0.82rem; color: var(--t-text2); line-height: 1.5; }

.pr-recent { display: grid; grid-template-columns: 1.3fr 1fr auto auto; gap: 0.5rem; align-items: center; padding: 0.5rem 0; border-bottom: 1px solid var(--t-border); font-size: 0.78rem; }
.pr-recent:last-child { border-bottom: none; }
.pr-recent-subj { font-weight: 600; color: var(--t-text1); }
.pr-recent-type { color: var(--t-text3); font-size: 0.7rem; }
.pr-recent-score { font-weight: 700; text-align: right; }
.pr-recent-date { color: var(--t-text3); font-size: 0.7rem; text-align: right; }

.pr-ai-hint { font-size: 0.82rem; color: var(--t-text3); margin-bottom: 0.75rem; }
.pr-ai-text { font-size: 0.88rem; color: var(--t-text1); line-height: 1.7; white-space: pre-wrap; }
.pr-ai-engine { font-size: 0.66rem; color: var(--t-accent); margin-top: 0.6rem; }

@media print {
  .pr-print, .btn-primary { display: none; }
}
</style>
